export const productsData = [
  {
    id: 0,
    title: "sdvjds",
    price: 15,
    quantity: 1,
    availableSizes: ["X", "M", "L"],
  },
  {
    id: 1,
    title: "dsfdf",
    price: 12,
    quantity: 1,
    availableSizes: ["XL", "M"],
  },
  {
    id: 2,
    title: "dsfo",
    price: 11,
    quantity: 1,
    availableSizes: ["X"],
  },
  {
    id: 3,
    title: "sdvjds",
    price: 17,
    quantity: 1,
    availableSizes: ["M"],
  },
  {
    id: 4,
    title: "sdvjds",
    price: 16,
    quantity: 1,
    availableSizes: ["M", "L"],
  },
  {
    id: 5,
    title: "dffdfege",
    price: 65,
    quantity: 1,
    availableSizes: ["X", "L"],
  },
  {
    id: 6,
    title: "wreeo",
    price: 25,
    quantity: 1,
    availableSizes: ["X", "M", "L"],
  },
  {
    id: 7,
    title: "sdvjds",
    price: 75,
    quantity: 1,
    availableSizes: ["X", "M", "L", "XL"],
  },
  {
    id: 8,
    title: "sdvds",
    price: 19,
    quantity: 1,
    availableSizes: ["X", "M", "L", "S"],
  },
  {
    id: 9,
    title: "woei",
    price: 335,
    quantity: 1,
    availableSizes: ["XL"],
  },
  {
    id: 10,
    title: "lowe",
    price: 120,
    quantity: 1,
    availableSizes: ["L"],
  },
];
